In [4]:
import pandas as pd

In [5]:
ls

15-jan-2022-exception-handling-and-logging.ipynb
19dec-python-program-discussion.ipynb
20-dec-python-program-discussion.ipynb
21-dec-python-program-discussion.ipynb
23-JAN-2022-OOPS.ipynb
23-dec-function.ipynb
26-FEB-2022-PANDAS.ipynb
29-JAN-2022-OOPS-ADVANCED.ipynb
30-JAN-2022-polymorphism-overload-override-static-custom-exceptions.ipynb
8-jan-python-functions-part-2.ipynb
9-jan-python-iterator-generator.ipynb
__pycache__/
basic-2-dec5.ipynb
basic-3-dec18-tuples-set-dict.ipynb
google.txt
mydict.py
pythonbasic-1-dec-4.ipynb
test.IPYNB
test.log
test.txt
test1.text
test1classdec4.ipynb

In [ ]:
pd.read

In [6]:
ls

15-jan-2022-exception-handling-and-logging.ipynb
19dec-python-program-discussion.ipynb
20-dec-python-program-discussion.ipynb
21-dec-python-program-discussion.ipynb
23-JAN-2022-OOPS.ipynb
23-dec-function.ipynb
26-FEB-2022-PANDAS.ipynb
29-JAN-2022-OOPS-ADVANCED.ipynb
30-JAN-2022-polymorphism-overload-override-static-custom-exceptions.ipynb
8-jan-python-functions-part-2.ipynb
9-jan-python-iterator-generator.ipynb
Sample.csv
__pycache__/
basic-2-dec5.ipynb
basic-3-dec18-tuples-set-dict.ipynb
google.txt
mydict.py
pythonbasic-1-dec-4.ipynb
test.IPYNB
test.log
test.txt
test1.text
test1classdec4.ipynb

In [8]:
pd.read_csv('Sample.csv')

        name        emailid address     pin surname
0  Sudhanshu  abc@gmail.com     RTM  457001   Kumar
1    Shubham  xyz@gmail.com    INDB  452001   DIXIT
2      Vayam  hjk@GMAIL.COM     UJN  454001    JAIN

In [21]:
df = pd.read_csv('/Users/shudixit/data-ml/sample-csv/taxonomy.csv')

In [22]:
# Pandas work with a concept called as Data frame like SQL uses tables and stuff

In [23]:
type(df)

pandas.core.frame.DataFrame

In [24]:
df ## See this is not a correct thing as frst row is not a column name

           101                     Emergency Unnamed: 2            Unnamed: 3
0       101-01             Disaster Response        101             Emergency
1       101-02                Emergency Cash        101             Emergency
2    101-02-01             Help Pay for Food     101-02        Emergency Cash
3    101-02-02       Help Pay for Healthcare     101-02        Emergency Cash
4    101-02-03          Help Pay for Housing     101-02        Emergency Cash
..         ...                           ...        ...                   ...
284  111-01-07              Workplace Rights     111-01  Advocacy & Legal Aid
285     111-02                     Mediation        111                 Legal
286     111-03                        Notary        111                 Legal
287     111-04                Representation        111                 Legal
288     111-05  Translation & Interpretation        111                 Legal

[289 rows x 4 columns]

In [26]:
df1 = pd.read_csv('taxonomy.csv', header=None) # No headers in the DataFrame
df1

             0                             1       2                     3
0          101                     Emergency     NaN                   NaN
1       101-01             Disaster Response     101             Emergency
2       101-02                Emergency Cash     101             Emergency
3    101-02-01             Help Pay for Food  101-02        Emergency Cash
4    101-02-02       Help Pay for Healthcare  101-02        Emergency Cash
..         ...                           ...     ...                   ...
285  111-01-07              Workplace Rights  111-01  Advocacy & Legal Aid
286     111-02                     Mediation     111                 Legal
287     111-03                        Notary     111                 Legal
288     111-04                Representation     111                 Legal
289     111-05  Translation & Interpretation     111                 Legal

[290 rows x 4 columns]

In [29]:
df2 = pd.read_csv('taxonomy.csv', names=['a', 'b', 'c', 'd']) # Custom header names, more or less columns will adjust accordingly
df2

             a                             b       c                     d
0          101                     Emergency     NaN                   NaN
1       101-01             Disaster Response     101             Emergency
2       101-02                Emergency Cash     101             Emergency
3    101-02-01             Help Pay for Food  101-02        Emergency Cash
4    101-02-02       Help Pay for Healthcare  101-02        Emergency Cash
..         ...                           ...     ...                   ...
285  111-01-07              Workplace Rights  111-01  Advocacy & Legal Aid
286     111-02                     Mediation     111                 Legal
287     111-03                        Notary     111                 Legal
288     111-04                Representation     111                 Legal
289     111-05  Translation & Interpretation     111                 Legal

[290 rows x 4 columns]

In [35]:
# Delimiter/Seprator can be anything other than comma if the file actually have it. Default is comma
df2 = pd.read_csv('Sample.csv', sep=',') 
df2

        name        emailid address     pin surname
0  Sudhanshu  abc@gmail.com     RTM  457001   Kumar
1    Shubham  xyz@gmail.com    INDB  452001   DIXIT
2      Vayam  hjk@GMAIL.COM     UJN  454001    JAIN

In [38]:
df2 = pd.read_csv('Sample.csv', skiprows=[1,3])

In [39]:
df2

      name        emailid address     pin surname
0  Shubham  xyz@gmail.com    INDB  452001   DIXIT

In [44]:
df = pd.read_csv('services.csv')

In [45]:
type(df)

pandas.core.frame.DataFrame

In [46]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [47]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [50]:
df.head(3) # just 5 records which gives the type of data from top

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN

In [51]:
df.tail(5) # just 5 records which gives the type of data from bottom

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [52]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [53]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [57]:
df['website'] # Particular column access

0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
5                        NaN
6                        NaN
7                        NaN
8                        NaN
9                        NaN
10                       NaN
11                       NaN
12                       NaN
13                       NaN
14                       NaN
15                       NaN
16                       NaN
17                       NaN
18                       NaN
19                       NaN
20                       NaN
21    http://www.example.com
22    http://www.example.com
Name: website, dtype: object

In [59]:
df['website']

0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
5                        NaN
6                        NaN
7                        NaN
8                        NaN
9                        NaN
10                       NaN
11                       NaN
12                       NaN
13                       NaN
14                       NaN
15                       NaN
16                       NaN
17                       NaN
18                       NaN
19                       NaN
20                       NaN
21    http://www.example.com
22    http://www.example.com
Name: website, dtype: object

In [61]:
a = df['name'] # COLUMNS ARE BY DEFAULT A SERIES
type(a)

pandas.core.series.Series

In [62]:
# DATAFRAMES ARE A COMBINATION OF SERIES

In [65]:
df[['name']]

                                    name
0        Fair Oaks Adult Activity Center
1       Second Career Employment Program
2                 Senior Peer Counseling
3               Family Visitation Center
4      Economic Self-Sufficiency Program
5   Little House Recreational Activities
6       Rosener House Adult Day Services
7         Meals on Wheels - South County
8                       Fair Oaks Branch
9                           Main Library
10                       Schaberg Branch
11                          Project Read
12                 Redwood Shores Branch
13                    Redwood City Corps
14           Adult Rehabilitation Center
15                       Sunnyvale Corps
16     South San Francisco Citadel Corps
17                         Project Smile
18         San Mateo Free Medical Clinic
19             Service with blank fields
20       Service for Admin Test Location
21                       Passport Photos
22                  Example Service Name

In [67]:
type(df[['name', 'email']])

pandas.core.frame.DataFrame

In [68]:
df[['name', 'email']] # Multiple column access

                                    name                  email
0        Fair Oaks Adult Activity Center                    NaN
1       Second Career Employment Program                    NaN
2                 Senior Peer Counseling                    NaN
3               Family Visitation Center                    NaN
4      Economic Self-Sufficiency Program                    NaN
5   Little House Recreational Activities                    NaN
6       Rosener House Adult Day Services                    NaN
7         Meals on Wheels - South County                    NaN
8                       Fair Oaks Branch                    NaN
9                           Main Library                    NaN
10                       Schaberg Branch                    NaN
11                          Project Read                    NaN
12                 Redwood Shores Branch                    NaN
13                    Redwood City Corps                    NaN
14           Adult Rehabilitation Center                    NaN
15                       Sunnyvale Corps                    NaN
16     South San Francisco Citadel Corps                    NaN
17                         Project Smile                    NaN
18         San Mateo Free Medical Clinic                    NaN
19             Service with blank fields                    NaN
20       Service for Admin Test Location                    NaN
21                       Passport Photos  passports@example.org
22                  Example Service Name                    NaN

In [ ]:
# SUMMARY
# Pandas work with a concept called as Data frame like SQL uses tables and stuff
# See this is not a correct thing as frst row is not a column name
# Delimiter/Seprator can be anything other than comma if the file actually have it. Default is comma
# COLUMNS ARE BY DEFAULT A SERIES
# DATAFRAMES ARE A COMBINATION OF SERIES
# df['website'] # Particular column access
# df.tail(5) # just 5 records which gives the type of data from bottom
# df.head(3) # just 5 records which gives the type of data from top